apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mee7.fullname" . }}-secret"
  labels:
    {{- include "mee7.labels" . | nindent 4 }}
type: Opaque
data:
  BotToken: "{{ .Values.mee7.token | b64enc }}"
